import pandas as pd
import time 

start_time = time.time()

planilha = r'/home/moesiosf/Área de trabalho/TRATAMENTO/BD.xlsx'
xls = pd.ExcelFile(planilha)

existing_sheets = pd.read_excel(planilha, sheet_name=None)

df_menu = pd.read_excel(planilha, sheet_name='MENU')
df_domicilio = pd.read_excel(planilha, sheet_name='DOMICÍLIO')
df_morador = pd.read_excel(planilha, sheet_name='MORADOR')
df_deslocamento = pd.read_excel(planilha, sheet_name='DESLOCAMENTO')



colunas_organizadas = [
    'DATA','ID_MENU','ID_DOMICILIO','TIPO DE DOMICÍLIO','QUANTAS PESSOAS MORAM NESSE DOMICÍLIO ?','QUANTAS FAMÍLIAS MORAM NESSE DOMICÍLIO ?','VERIFICAÇÃO DOS ITENS DE CONFORTO PREENCHIDOS',
    'AJUSTADO','GELADEIRA','FREEZER','LAVA-LOUÇAS','MÁQUINA DE LAVAR ROUPA','MÁQUINA DE SECAR ROUPA','MICRO-ONDAS','COMPUTADOR/NOTEBOOK','DVD/VIDEOGAME','BANHEIROS','QUANTOS EMPREGADOS DOMÉSTICOS QUE TRABALHAM PELO MENOS 5 DIAS POR SEMANA',
    'BICICLETAS','MOTOCICLETAS','AUTOMÓVEIS','TEM ÁGUA ENCANADA NESTE DOMICÍLIO ?','QTD_PESSOAS_MORADOR','VALIDAÇÃO'
]


colunas_organizadas_2 = [
    'DATA','ID_MENU', 'ID_DOMICILIO', 'ID_MORADOR', 'PRIMEIRO NOME',
    'QUANTOS DESLOCAMENTOS VOCÊ FEZ ONTEM ?', 'verificação deslocamentos cadastrados',
    'SITUAÇÃO FAMILIAR', 'OUTROS(1)', 'GÊNERO', 'IDADE', 'QUAL GRAU DE INSTRUÇÃO ?',
    'ESTUDANTE?', 'AULAS ONLINE ?', 'SABE INFORMAR O NOME DO LOCAL ONDE ESTUDA ?',
    'NOME DO LOCAL ONDE ESTUDA', 'SABE INFORMAR O NOME E NÚMERO DO LOGRADOURO ONDE ESTUDA ?',
    'NOME DO LOGRADOURO ONDE ESTUDA ?', 'QUAL NOME DA OUTRA RUA ?', 'BAIRRO ONDE ESTUDA',
    'MUNICÍPIO ONDE ESTUDA', 'QUAL O TIPO DE INSTITUIÇÃO ?', 'CONDIÇÃO DE ATIVIDADE PRINCIPAL',
    'TRABALHO HOME OFFICE ?', 'SABE INFORMAR O NOME DO LOCAL DE TRABALHO ?', 'NOME DO TRABALHO',
    'SABE INFORMAR O NOME E NÚMERO DO LOGRADOURO DO TRABALHO', 'NOME DO LOGRADOURO(TRABALHO)',
    'QUAL OUTRA RUA ?', 'BAIRRO(TRABALHO)', 'MUNICÍPIO(TRABALHO)', 'CONDIÇÃO DA ATIVIDADE SECUNDÁRIA',
    'TRABALHO (2) HOME OFFICE ?', 'NOME DO TRABALHO(2)', 'NOME DO LOCAL - TRABALHO (2)',
    'SABE INFORMAR O NOME E NÚMERO DO LOGRADOURO DO TRABALHO(2)', 'NOME DO LOGRADOURO - TRABALHO(2)',
    'NÚMERO DO LOGRADOURO - TRABALHO(2)', 'SABE INFORMAR O BAIRRO - TRABALHO(2)', 'BAIRRO - TRABALHO(2)',
    'MUNICÍPIO - TRABALHO(2)', 'OUTRO MUNICÍPIO - TRABALHO(2)', 'RENDA', 'POSSUI LIMITAÇÕES DE MOBILIDADE',
    'VOCÊ SE ENVOLVEU EM ALGUM ACIDENTE DE TRÂNSITO NOS ÚLTIMOS 12 MESES ?', 'QUAL MODO DE TRANSPORTE VOCÊ ESTAVA UTILIZANDO NO MOMENTO DO ACIDENTE ?',
    'OUTRO (2)', 'QUAL MODO DE TRANSPORTE DO(S) OUTRO(S) ENVOLVIDO(S) NO ACIDENTE ?', 'OUTRO (3)',
    'TEVE ALGUMA LESÃO PERMANENTE APÓS O ACIDENTE ?', 'MUNICÍPIO DO ACIDENTE', 'POR QUE VOCÊ NÃO FEZ NENHUM DESLOCAMENTO ONTEM ?',
    'OUTROS ?', 'NACIONALIDADE', 'OUTRO MUNICÍPIO - ESTUDO', 'NÚMERO DO LOGRADOURO ONDE ESTUDA',
    'OUTRO MUNICÍPIO - TRABALHO', 'NÚMERO DO LOGRADOURO - TRABALHO', 'BAIRRO DO ACIDENTE',
    'NOME DO LOGRADOURO DO ACIDENTE', 'NÚMERO DO LOGRADOURO DO ACIDENTE', 'RAÇA', 'SABE INFORMAR O BAIRRO ?',
    'verificação estudante', 'verificação trabalho', 'ENDEREÇO ESCOLA CONCETANADO', 'ENDEREÇO TRABALHO 1',
    'ENDEREÇO TRABALHO 2'
]


colunas_organizadas_3=[
    'DATA','ID_MENU','ID_DOMICILIO','ID_MORADOR','ID_Deslocamento','ORIGEM','ENDEREÇO_ORIGEM_BRUTO','ENDEREÇO ORIGEM GEOCODIFICADO','LATITUDE ORIGEM','LONGITUDE ORIGEM','INFORMOU PONTO DE REFERÊNCIA',
    'PONTO DE REFERÊNCIA','SABE INFORMAR O LOCAL DE ORIGEM','ENDEREÇO DE ORIGEM','QUAL O NÚMERO DO LOCAL DE ORIGEM ?','BAIRRO DA ORIGEM','MUNICÍPIO DA ORIGEM','QUAL O MUNICÍPIO DO LOCAL DE ORIGEM ?','OUTRO MOTIVO(ORIGEM)','MOTIVO (ORIGEM)',
    'DESTINO','QUANTIDADE DE VIAGENS','ENDEREÇO_DESTINO_BRUTO','ENDEREÇO DESTINO GEOCODIFICADO','LATITUDE DESTINO','LONGITUDE DESTINO','INFORMOU PONTO DE REFERÊNCIA(DESTINO)','PONTO DE REFERÊNCIA(DESTINO)','ENDEREÇO DO DESTINO',
    'QUAL O LOGRADOURO DO LOCAL DO DESTINO','QUAL O NÚMERO DO LOCAL ?','SABE INFOMAR O BAIRRO DO LOCAL(DESTINO)','QUAL O BAIRRO DO LOCAL(DESTINO)','MUNICÍPIO DO LOCAL DE DESTINO','OUTRO MOTIVO(DESTINO)',
    'MOTIVO(DESTINO)','QUE HORAS VOCÊ CHEGOU NO DESTINO ?','NESSE DESLOCAMENTO, QUAL O PRINCIPAL MODO DE TRANSPORTE UTILIZADO? (AQUELE UTILIZADO POR MAIOR TEMPO/ MAIOR DISTÂNCIA)','OUTROS','NESSE DESLOCAMENTO, HOUVE OUTRO MODO DE TRANSPORTE?',
    'OUTROS.1','QUANTOS MINUTOS ANDOU DO LOCAL DE ORIGEM AO PONTO DE ÔNIBUS ?','QUANTOS MINUTOS ANDOU DO PONTO DE ÔNIBUS ATÉ LOCAL DE DESTINO?','QUANTOS MINUTOS EM MÉDIA FICA ESPERANDO NO PONTO DE ÔNIBUS ?','FORMA DE PAGAMENTO','ONDE VOCÊ ESTACIONOU NO LOCAL DE DESTINO ?',
    'COMENTÁRIOS','CATEGORIA'
]

df_domicilio=df_domicilio[colunas_organizadas]
df_morador=df_morador[colunas_organizadas_2]
df_deslocamento=df_deslocamento[colunas_organizadas_3]

with pd.ExcelWriter(planilha, engine='openpyxl', mode='a', if_sheet_exists='replace') as writer:
    df_morador.to_excel(writer, sheet_name='MORADOR', index=False)
    df_domicilio.to_excel(writer, sheet_name='DOMICÍLIO', index=False)
    df_deslocamento.to_excel(writer, sheet_name='DESLOCAMENTO', index=False)

end_time = time.time()
execution_time = end_time - start_time 
print(execution_time)    